"""LLM copilot for the AI flight assistant (OpenAI-compatible chat completions).

Wraps the offline rule engine with an optional LLM backend:

  * chat answers are generated by the model, grounded in a compact live
    telemetry context; ANY failure (no endpoint, refused connection,
    timeout, malformed response) falls back to the rule-based
    `PilotAssistant`, so the assistant always answers.
  * the dashboard "AI suggestions" panel is drafted by the model from the
    active alerts, rate-limited on a background thread so the 10 Hz sim
    loop never blocks; until a draft lands (or if the LLM is down) the
    rule suggestions are shown unchanged.

Only stdlib networking (`urllib`) is used so the simulator stays dependency
free. The endpoint defaults to a LOCAL Ollama instance
(http://127.0.0.1:11434/v1) — by default nothing leaves the machine, and
any OpenAI-compatible server can be pointed to via `base_url`.

Architecture guarantee unchanged: this module only ever produces TEXT. It
imports nothing from the flight controller and holds no reference to
controls, actuators or the autopilot — the copilot can never actuate the
aircraft.
"""

import json
import math
import threading
import time
import urllib.request

from simulator.config import LLM as _LLM_CFG, PISTON_ENGINE
from simulator.ai_advisor.monitor import PilotAssistant, KT

_PROBE_TIMEOUT_S = 2.0
_PROBE_OK_COOLDOWN_S = 300.0
_PROBE_FAIL_COOLDOWN_S = 30.0

_SYS = (
    "You are the AI flight assistant on a piston-engine UAV flight simulator. "
    "You watch engine, fuel, flight envelope, navigation, wind and no-fly "
    "zones in real time and advise the pilot. HARD RULES: "
    "(1) you can only ADVISE — you have no connection to the aircraft controls "
    "and must never claim to have changed anything or to be flying the UAV; "
    "(2) ground every answer in the telemetry context provided; if the data "
    "does not answer the question, say so plainly instead of inventing "
    "numbers; (3) be concise — at most ~120 words; (4) be specific, using "
    "units from the context (kt, m, %, RPM, C)."
)


class LlmCopilot:
    """AI flight assistant: LLM-first chat + suggestion drafting, rules fallback."""

    def __init__(self, base_url=None, model=None, api_key=None, enabled=True,
                 rules=None, timeout_s=None, suggest_interval_s=None):
        self.base_url = (base_url if base_url is not None
                         else _LLM_CFG["base_url"]).rstrip("/")
        self.model = model or _LLM_CFG["model"]
        self.api_key = api_key if api_key is not None else _LLM_CFG["api_key"]
        self.enabled = bool(enabled)
        self.timeout_s = timeout_s or _LLM_CFG["timeout_s"]
        self.suggest_interval_s = (suggest_interval_s
                                   or _LLM_CFG["suggest_interval_s"])
        self.rules = rules if rules is not None else PilotAssistant()

        self._available = None          # None = untested, True/False = known
        self._probe_at = 0.0
        self._last_err = None           # timestamp of last LLM failure
        self._lock = threading.Lock()
        self._sug = {"sig": "", "at": 0.0, "items": [], "llm": False}
        self._sug_busy = False

    # ------------------------------------------------------------------ #
    # availability / metadata                                            #
    # ------------------------------------------------------------------ #
    def _headers(self):
        h = {"Content-Type": "application/json"}
        if self.api_key:
            h["Authorization"] = "Bearer " + self.api_key
        return h

    def _probe_sync(self):
        """Check the endpoint is reachable. Cached with a cooldown so a dead
        endpoint is not hammered, and a recovered one is re-detected."""
        now = time.time()
        if self._available is not None and now < self._probe_at:
            return self._available is True
        ok = False
        try:
            req = urllib.request.Request(self.base_url + "/models",
                                         headers=self._headers())
            with urllib.request.urlopen(req, timeout=_PROBE_TIMEOUT_S) as r:
                ok = r.status == 200
        except Exception:
            ok = False
        self._available = ok
        self._probe_at = now + (_PROBE_OK_COOLDOWN_S if ok
                                else _PROBE_FAIL_COOLDOWN_S)
        return ok

    @property
    def available(self):
        """True once the endpoint has been probed successfully. Never blocks."""
        return self._available is True

    def meta(self):
        """Status snapshot for the dashboard badge."""
        return {
            "llm": self.available,
            "model": self.model,
            "base_url": self.base_url,
            "status": "probing" if self._available is None else "probed",
        }

    # ------------------------------------------------------------------ #
    # chat                                                                #
    # ------------------------------------------------------------------ #
    def answer(self, text, s, assessment):
        """Answer the pilot's question. LLM when available, else rules."""
        if not s or not assessment:
            return "No telemetry received yet — start the simulator first."
        if self.enabled and self._probe_sync():
            try:
                ctx = self._context(s, assessment)
                msgs = [
                    {"role": "system", "content": _SYS},
                    {"role": "user", "content": (
                        f"Live telemetry + assessment:\n{ctx}\n\n"
                        f"Pilot asks: {str(text)[:500]}\n\n"
                        "Answer the pilot.")},
                ]
                return self._chat(msgs, max_tokens=400, temperature=0.4)
            except Exception as ex:
                self._note_failure(ex, "chat")
        return self.rules.answer(text, s, assessment)

    # ------------------------------------------------------------------ #
    # suggestions panel (rate-limited, background thread)                #
    # ------------------------------------------------------------------ #
    def refresh_suggestions(self, assessment, s=None):
        """Non-blocking refresh of the suggestions panel, called at 10 Hz.

        Returns the current cache — the LLM draft once one exists for the
        current alert set, the rule suggestions until then. Never blocks the
        sim loop: the draft runs on a daemon thread.
        """
        alerts = assessment.get("alerts") or []
        sig = "|".join(sorted(str(a.get("id", "")) for a in alerts))
        now = time.time()
        rule_items = assessment.get("suggestions") or []
        with self._lock:
            c = self._sug
            if c["sig"] == sig and now - c["at"] < self.suggest_interval_s:
                return c["items"]
            if self._sug_busy:
                return rule_items   # draft in flight for this alert set
            if (not self.enabled
                    or (self._available is False and now < self._probe_at)):
                if c["sig"] != sig:
                    # cache the rule set so a dead LLM never blanks the panel
                    self._sug = {"sig": sig, "at": now,
                                 "items": rule_items, "llm": False}
                return rule_items
            self._sug_busy = True
        threading.Thread(target=self._draft, args=(assessment, s, sig),
                         daemon=True, name="ai-suggestions").start()
        return rule_items

    def _draft(self, assessment, s, sig):
        items = assessment.get("suggestions") or []
        llm = False
        try:
            if self._probe_sync():
                ctx = self._context(s, assessment)
                msgs = [
                    {"role": "system", "content": _SYS},
                    {"role": "user", "content": (
                        f"Live flight assessment:\n{ctx}\n\n"
                        "Write up to 4 short pilot suggestion cards for the "
                        "dashboard 'AI suggestions' panel. Reply with ONLY a "
                        "JSON array of objects [{\"title\": ..., \"detail\": "
                        "...}] — no prose, no code fences. Titles are short "
                        "imperatives ('Reduce power'); details are one "
                        "sentence with numbers from the context. If "
                        "everything is nominal, reply [].")},
                ]
                parsed = self._parse_suggestions(
                    self._chat(msgs, max_tokens=400, temperature=0.3))
                if parsed is not None:
                    items, llm = parsed, True
        except Exception as ex:
            self._note_failure(ex, "suggestions")
        finally:
            with self._lock:
                self._sug = {"sig": sig, "at": time.time(),
                             "items": items, "llm": llm}
                self._sug_busy = False

    @staticmethod
    def _parse_suggestions(text):
        """Extract a JSON array of {title, detail} from an LLM reply.

        Tolerant of code fences, surrounding prose and trailing commas.
        Returns None when the reply is not usable (caller keeps rules)."""
        if not text:
            return None
        t = text.strip()
        if t.startswith("```"):
            rest = t[3:]
            if rest.startswith("json"):
                rest = rest[4:]
            end = rest.find("```")
            t = rest if end < 0 else rest[:end]
        i, j = t.find("["), t.rfind("]")
        if i < 0 or j <= i:
            return None
        try:
            data = json.loads(t[i:j + 1])
        except (ValueError, TypeError):
            return None
        out = []
        for d in data if isinstance(data, list) else []:
            if not isinstance(d, dict) or not d.get("title"):
                continue
            out.append({
                "id": "LLM",
                "title": str(d["title"])[:80],
                "detail": str(d.get("detail", ""))[:200],
                "source_alert": "LLM-drafted",
            })
        return out if out else []

    # ------------------------------------------------------------------ #
    # internals                                                          #
    # ------------------------------------------------------------------ #
    def _chat(self, messages, max_tokens=400, temperature=0.4):
        body = json.dumps({
            "model": self.model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
            # Ollama extension: keep the model loaded between chats so the
            # next answer doesn't pay the model-load latency again.
            "keep_alive": "30m",
        }).encode("utf-8")
        req = urllib.request.Request(
            self.base_url + "/chat/completions", data=body,
            headers=self._headers(), method="POST")
        with urllib.request.urlopen(req, timeout=self.timeout_s) as r:
            data = json.loads(r.read().decode("utf-8", "replace"))
        return str(data["choices"][0]["message"]["content"]).strip()

    def _note_failure(self, ex, what):
        now = time.time()
        if self._last_err is None or now - self._last_err > 30:
            print(f"[ai] LLM {what} failed ({ex}); using offline rules.")
        self._last_err = now
        self._available = False
        self._probe_at = now + _PROBE_FAIL_COOLDOWN_S

    def _context(self, s, assessment):
        """Compact telemetry + assessment text to ground the LLM."""
        s = s or {}
        ins = assessment.get("insights", {})
        ov = assessment.get("overall", {})
        eng = s.get("engine_summary") or {}
        es = s.get("engine_sensors") or {}
        pit = s.get("pitot_reading") or {}
        gps = s.get("gps") or {}
        alerts = assessment.get("alerts") or []
        sugs = assessment.get("suggestions") or []
        lines = []
        lines.append(f"Overall health: {ov.get('score', '?')}/100 "
                     f"({ov.get('status', '?')}). {ov.get('summary', '')}")
        if alerts:
            lines.append("Alerts: " + "; ".join(
                f"[{a.get('sev')}] {a.get('msg')}" for a in alerts[:6]))
        if sugs:
            lines.append("Current suggestions: " + "; ".join(
                str(x.get("title", "")) for x in sugs[:4]))
        lines.append(
            f"Flight: mode {s.get('mode')}, IAS {pit.get('ias_mps', 0) * KT:.0f} kt, "
            f"baro {pit.get('baro_alt_msl_m', 0):.0f} m MSL, "
            f"AGL {ins.get('agl_m', '?')} m, "
            f"VS {pit.get('vsi_mps', 0) * 196.85:+.0f} fpm")
        if ins.get("endurance_min") is not None:
            lines.append(
                f"Fuel: {es.get('fuel_qty_L', 0):.0f} L, "
                f"flow {ins.get('fuel_flow_lph', 0):.1f} L/h, "
                f"endurance ~{ins.get('endurance_min', 0) / 60:.1f} h"
                + (f", range {ins.get('range_km', 0):.0f} km, home fuel "
                   f"{ins.get('fuel_home_L', 0):.1f} L "
                   f"(reachable: {ins.get('can_reach_home')})"
                   if ins.get("fuel_home_L") is not None else ""))
        lines.append(
            f"Engine: {'RUNNING' if eng.get('running') else 'OFF'}, "
            f"{es.get('rpm', 0):.0f} RPM, {eng.get('power_kw', 0):.1f} kW, "
            f"CHT {es.get('cht_C', 0):.0f} C (limit {PISTON_ENGINE['cht_max_c']}), "
            f"EGT {es.get('egt_C', 0):.0f} C, oil {es.get('oil_psi', 0):.0f} psi, "
            f"stall margin {ins.get('stall_margin_kt', '?')} kt")
        if gps:
            lines.append(f"GPS: {gps.get('health')} "
                         f"({gps.get('satellites')} sats, "
                         f"HDOP {gps.get('hdop', 0):.2f})")
        # These two arrive as numpy arrays in the raw sim snapshot (only the
        # published copy is converted to lists), so they are length-tested
        # rather than truth-tested — `if w:` on an ndarray raises ValueError.
        nfz = s.get("nfz_violations")
        if nfz is not None and len(nfz):
            lines.append(f"NFZ: BREACHING {nfz[0].get('name')} by "
                         f"{nfz[0].get('penetration_m', 0):.0f} m")
        w = s.get("wind_ned")
        if w is not None and len(w) >= 2:
            spd = math.hypot(w[0], w[1])
            frm = (math.degrees(math.atan2(-w[1], -w[0])) + 360.0) % 360.0
            lines.append(f"Wind: {spd:.1f} m/s from {frm:.0f} deg")
        if s.get("mission_count"):
            lines.append(f"Mission: wp {s.get('mission_current_idx', 0) + 1}/"
                         f"{s['mission_count']}, {s.get('mission_dist_m')} m, "
                         f"bearing {s.get('mission_bearing_deg', 0)} deg")
        return "\n".join(lines)